// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using final_project.Models;

namespace final_project.Migrations
{
    [DbContext(typeof(D2RandomContext))]
    partial class D2RandomContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("final_project.Armor", b =>
                {
                    b.Property<int>("ArmorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aname")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(60);

                    b.HasKey("ArmorID");

                    b.ToTable("Armor");
                });

            modelBuilder.Entity("final_project.Heavy", b =>
                {
                    b.Property<int>("HeavyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hname")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(60);

                    b.HasKey("HeavyID");

                    b.ToTable("Heavy");
                });

            modelBuilder.Entity("final_project.Primary", b =>
                {
                    b.Property<int>("PrimaryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pname")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(60);

                    b.HasKey("PrimaryID");

                    b.ToTable("Primary");
                });

            modelBuilder.Entity("final_project.Secondary", b =>
                {
                    b.Property<int>("SecondaryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sname")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(60);

                    b.HasKey("SecondaryID");

                    b.ToTable("Secondary");
                });
#pragma warning restore 612, 618
        }
    }
}
